# Generated by Django 3.0.3 on 2020-08-05 21:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200805_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pubished_date',
            new_name='published_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 21, 23, 37, 918395, tzinfo=utc)),
        ),
    ]
